CHANGE(netdata): Add security limits
open-io/ansible-role-openio-netdata pull request #67
Opened 2019-12-03 13:11 UTC by GeoffreyTien

##### SUMMARY

- add new variables to set open files limit used by netdata
- increase The default operating system limits on mmap
- change check lib zookeeper on command.conf

 ##### IMPACT

 ##### ADDITIONAL INFORMATION

2019-12-03 13:23 UTC, vdombrovski requested changes

2019-12-03 13:23 UTC, vdombrovski commented on files/commands/RedHat.conf
> +zk_lib_version=rpm -q --qf "%{VERSION}\n" libzookeeper2
Out of scope for PR

2019-12-03 13:23 UTC, vdombrovski commented on tasks/main.yml
> +  when: inventory_hostname in openio_netdata_oio_hosts
This needs to be applied everywhere, not only on OpenIO hosts

2019-12-03 13:23 UTC, vdombrovski commented on tasks/main.yml
> +  when: inventory_hostname in openio_netdata_oio_hosts
Same as below

2019-12-03 13:23 UTC, vdombrovski commented on tasks/main.yml
> +  when: inventory_hostname in openio_netdata_oio_hosts
Also, don't forget to reload sysctl when modifying the configuration. In fact, you can use sysctl module to set these parameters like this:

```
sysctl:
        sysctl_file: "/etc/sysctl.d/netdata.conf"
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: true
        reload: true
```

2019-12-04 14:26 UTC, vdombrovski commented on files/commands/RedHat.conf
> +zk_lib_version=rpm -q --qf "%{VERSION}\n" libzookeeper2
See #69

2019-12-05 15:01 UTC, cdelgehier requested changes

2019-12-05 15:01 UTC, cdelgehier commented on tasks/main.yml
> +  tags: configure
`when: openio_security_limits_managed`

2019-12-05 15:01 UTC, cdelgehier commented on tasks/main.yml
> +  tags: configure
`when: openio_sysctl_managed`

2019-12-05 15:01 UTC, cdelgehier commented on templates/python.d.conf.j2
> +
?

2019-12-05 15:01 UTC, cdelgehier commented on files/commands/RedHat.conf
> +zk_lib_version=rpm -q --qf "%{VERSION}\n" zookeeper-lib
?

2020-01-28 10:55 UTC, closed without merging